### PR TITLE
footer_at_bottom

### PR DESCRIPTION
**Pull request by Eklavya-sus**
issue #12

### CODE REVIEW

**Review by imhardikdesai — CHANGES_REQUESTED** [review]
@Eklavya-sus it is not proper spacing in mobile view. Can you fix this in all screen

**Comment by Eklavya-sus** [comment]
sure sure

**Comment by Eklavya-sus** [comment]
fixed, also made contact bg image cover whole screen

**Review by imhardikdesai — APPROVED** [review]
You did a great work, Thank You

**Comment by Eklavya-sus** [comment]
thank you so much for merging it

**Pull request merged**
